### ISSUE TITLE
Implementare CSS

### ISSUE THREAD

**Issue by AlessandroSCPse** [AlessandroSCPse/ale-team-git#2]
@LorenzoVeropalumbo Migliora il design dopo che @DavidePisani ha completato l'html.

Davide per piacere facci sapere quando hai finito tua task.

**Comment by DavidePisani** [comment]
Ciao @LorenzoVeropalumbo  ho finito l'index divertiti sul css,
Ho fatto il merge su master quindi trovi tutto su master

**Comment by LorenzoVeropalumbo** [comment]
@DavidePisani ho finito lo styling della pagina nel brach css-style

**Comment by DavidePisani** [comment]
Ok @LorenzoVeropalumbo ho contollato il lavoro, tutto ok puoi fare il merge, Grazie mille

**Comment by LorenzoVeropalumbo** [comment]
@DavidePisani marge effettuato grazie mille :)
